### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by synicalsyntax**

### CODE REVIEW

**Comment by zulipbot-test** [comment]
test

**Comment by synicalsyntax** [comment]
Reference #24

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/undefined members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/undefined members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this undefined needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this undefined needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this pull request needs your attention!

**Pull request closed without merging**
