### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by synicalsyntax**

### CODE REVIEW

**Comment by synicalsyntax** [comment]
@zulipbot label "area: emoji"

**Comment by synicalsyntax** [comment]
@zulipbot abandon

**Comment by synicalsyntax** [comment]
@zulipbot remove "area: emoji"

**Comment by synicalsyntax** [comment]
#24

**Comment by synicalsyntax** [comment]
#28

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs, @zulipbot-testing/server-emoji members, this pull request references an issue with the **area: documentation (user)", "area: emoji** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
#28

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs, @zulipbot-testing/server-emoji members, this pull request references an issue with the "area: documentation (user)", "area: emoji" labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs, @zulipbot-testing/server-emoji members, this pull request references an issue with the "area: documentation (user)", "area: emoji" labels, so you may want to check it out!

**Pull request closed without merging**
