### PR TITLE
Synicalsyntax patch 1

### PR DESCRIPTION
**Pull request by synicalsyntax**

### CODE REVIEW

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-development, @zulipbot-testing/server-hotkeys members, this issue was labeled with the **area: documentation (developer)**, **area: hotkeys** labels, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-misc members, this pull request references an issue with the "area: topics" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-hotkeys members, this pull request references an issue with the "area: hotkeys" label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot-test remove "bug"

**Pull request closed without merging**
