### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by synicalsyntax**

### CODE REVIEW

**Comment by zulipbot-test** [comment]
Congratulations, the Travis builds for this pull request **passed**!
Review the [build logs](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207829088) for more details.

**Comment by zulipbot-test** [comment]
Oh no, something wrong happened; the Travis builds for this pull request **errored**!
Review the [build logs](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207824924) for more details.

**Comment by zulipbot-test** [comment]
Congratulations, the Travis [builds](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207829088) for this pull request **passed**!

**Comment by zulipbot-test** [comment]
Oh no, something wrong happened; the Travis builds for this pull request **errored**! Review the [build logs](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207824924) for more details.

**Comment by zulipbot-test** [comment]
Congratulations, the Travis [builds](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207829088) for this pull request **passed**!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
@zulipbot label "travis updates"

**Comment by zulipbot-test** [comment]
Congratulations, the Travis [builds](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207829088) for this pull request **passed**!

**Comment by synicalsyntax** [comment]
@zulipbot remove "travis updates"

**Comment by zulipbot-test** [comment]
Oh no, something went wrong: the Travis builds for this pull request **failed**! Review the [build logs](fgsnfgshsfghhg) for more details.

**Comment by zulipbot-test** [comment]
Oh no, something went wrong: the Travis builds for this pull request **errored**! Review the [build logs](http://clin-dump.co.nf) for more details.

**Comment by zulipbot-test** [comment]
Congratulations, the Travis [builds](https://travis-ci.org/zulipbot-testing/synicalsyntax/builds/207829088) for this pull request **passed**!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this issue was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this undefined was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this undefined was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this pull request was labeled with the **area: documentation (user)** label, so you may want to check it out!

**Pull request closed without merging**
