### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by synicalsyntax**

### CODE REVIEW

**Comment by zulipbot-test** [comment]
Hello @synicalsyntax, it seems like you have referenced an issue in your pull request, but you have not referenced that issue in your commit message(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `"Fixes #[issue number]”`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: zulipbot
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51
```

Thank you for your contributions to Zulip!

**Comment by synicalsyntax** [comment]
test

**Comment by zulipbot-test** [comment]
Heads up @synicalsyntax, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/zulipbot-testing/synicalsyntax/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](http://zulip.readthedocs.io/en/latest/git-guide.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by zulipbot-test** [comment]
Hello @synicalsyntax, it seems like you have referenced an issue in your pull request, but you have not referenced that issue in your commit message(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `"Fixes #[issue number]”`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: zulipbot
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51
```

Thank you for your contributions to Zulip!

**Comment by zulipbot-test** [comment]
Heads up @synicalsyntax, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/zulipbot-testing/synicalsyntax/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](http://zulip.readthedocs.io/en/latest/git-guide.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by zulipbot-test** [comment]
Hello @synicalsyntax, it seems like you have referenced an issue in your pull request, but you have not referenced that issue in your commit message(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `"Fixes #[issue number]”`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: zulipbot
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51
```

Thank you for your contributions to Zulip!

**Comment by zulipbot-test** [comment]
Hello @synicalsyntax, it seems like you have referenced an issue in your pull request, but you have not referenced that issue in your commit message(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `"Fixes #[issue number]”`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: zulipbot
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51
```

Thank you for your contributions to Zulip!

**Comment by zulipbot-test** [comment]
Heads up @synicalsyntax, we just merged some commits that conflict with the changes your made in this pull request! You can review this repository's [recent commits](https://github.com/zulipbot-testing/synicalsyntax/commits/master) to see where the conflicts occur. Please rebase your feature branch against the `upstream/master` branch and [resolve](http://zulip.readthedocs.io/en/latest/git-guide.html#recover-from-a-git-rebase-failure) your pull request's merge conflicts accordingly.

**Comment by zulipbot-test** [comment]
Hello @synicalsyntax, it seems like you have referenced an issue in your pull request, but you have not referenced that issue in your commit message(s). When you reference an issue in a commit message, it automatically closes the corresponding issue when the commit is merged.

Please run `git commit --amend` in your command line client to amend your commit message description with `"Fixes #[issue number]”`.

An example of a correctly-formatted commit:
```
commit fabd5e450374c8dde65ec35f02140383940fe146
Author: zulipbot
Date:   Sat Mar 18 13:42:40 2017 -0700

    pull requests: Check PR commits reference when issue is referenced.

    Fixes #51
```

Thank you for your contributions to Zulip!

**Comment by zulipbot-test** [comment]
Oh no, something went wrong: the Travis builds for this pull request **failed**!

**Comment by zulipbot-test** [comment]
Oh no, something went wrong: the Travis builds for this pull request **failed**!

**Comment by zulipbot-test** [comment]
Oh no, something went wrong: the Travis builds for this pull request **failed**! Review the [build logs](http://google.com) for more details.

**Comment by zulipbot-test** [comment]
Hello @@zulipbot-testing/ members, this pull request was labeled with the **** s, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @@zulipbot-testing/server-hotkeys, @zulipbot-testing/server-misc members, this pull request was labeled with the **area: hotkeys**, **area: topics** s, so you may want to check it out!

**Pull request closed without merging**
