### PR TITLE
Update README.md

### LINKED ISSUE #24: PR
pr

### PR DESCRIPTION
**Pull request by synicalsyntax**
Fixes #24

### CODE REVIEW

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this pull request needs your attention!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request needs your attention!

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot claim

**Pull request closed without merging**
