### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by synicalsyntax**
#28

### CODE REVIEW

**Comment by synicalsyntax** [comment]
#47

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request references an pull request with the "area: emoji" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request references an pull request with the "area: emoji" label, so you may want to check it out!

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request references an issue with the "area: emoji" label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
#47

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-emoji members, this pull request was labeled with the **area: emoji** label, so you may want to check it out!

**Comment by synicalsyntax** [comment]
#47

**Comment by zulipbot-test** [comment]
Hello @zulipbot-testing/server-user-docs members, this pull request was labeled with the **area: documentation (user)** label, so you may want to check it out!

**Pull request closed without merging**
